Squashed and adapted commits for clear recents button on recents app screen
    Author: Adnan Begovic <adnan@cyngn.com>
    Date:   Thu Feb 19 17:38:35 2015 -0800

        SystemUI: Check if a task's group is null prior to TaskGrouping#isFrontMostTask.

            java.lang.NullPointerException: Attempt to invoke virtual method 'boolean
            com.android.systemui.recents.model.TaskGrouping.isFrontMostTask(com.android.systemui.recents.model.Task)' on a null object reference
              at com.android.systemui.recents.views.RecentsView.onTaskViewClicked(RecentsView.java:535)
              at com.android.systemui.recents.views.TaskStackView.onTaskViewClicked(TaskStackView.java:1125)
              at com.android.systemui.recents.views.TaskView.onClick(TaskView.java:881)
              at android.view.View.performClick(View.java:4756)
              at android.view.View$PerformClick.run(View.java:19749)
              at android.os.Handler.handleCallback(Handler.java:739)
              at android.os.Handler.dispatchMessage(Handler.java:95)

        Change-Id: I04afec21a7c4e7ba5b3e51ae76a2065e98e6cfa2

    Author: Altaf-Mahdi <altaf.mahdi@gmail.com>
    Date:   Sat Dec 20 23:15:21 2014 +0000

        SystemUI: Option to disable recents search bar (1/2)
        * also clean up hiding search bar
        * also make sure to add search bar view

    Author: Altaf-Mahdi <altaf.mahdi@gmail.com>
    Date:   Sun Apr 12 18:56:25 2015 +0100

        SystemUI: allow recent tasks to draw behind the status bar

        This also makes tasks draw behind the search bar if enabled

    Author: Jorge Ruesga <jorge@ruesga.com>
    Date:   Thu Apr 9 23:31:34 2015 +0100
    systemui: animate clear recents exit

        Currently, the animation just clear all the tasks at the same time. Just add
        a delay between every task remove call, and hide clear recents before start
        any animation.

    Author: Janson Kang <temasek71@gmail.com>
    Date:   Sun Jan 4 17:34:24 2015 +0800

        SystemUI: update clear all position & add top center/bottom center

        Credit: westcripp

    Author: Altaf-Mahdi <altaf.mahdi@gmail.com>
    Date:   Fri Jan 2 00:01:05 2015 +0000

        SystemUI: replace recents clear all button with a fab button

        * this allows us to have it any corner
        * added bottom right/left options

    Author: cristianomatos <cristianobmatos@gmail.com>
    Date:   Wed Nov 26 12:04:44 2014 -0200

        [Base]: recents panel clear all button tweaks

        - Show or hide recents button
        - Place the button in top right or left

    Author: Danny Baumann <dannybaumann@web.de>
    Date:   Wed Nov 19 20:19:18 2014 +0100

        Fix up 'clear recents' UX.

        Use the 'dismiss all' button drawable and place the button in the upper
        right corner. Doing so fixes the broken animation when going into
        recents.

    Author: Raj Yengisetty <rajesh@cyngn.com>
    Date:   Tue Nov 18 11:38:59 2014 -0800

        Fix - place Clear Recents button above the nav bar

    Author: Clark Scheff <clark@cyngn.com>
    Date:   Fri Nov 14 09:44:51 2014 -0800

    Add clear all recents action to recents panel

        Change-Id: I2243ebc83abc483e78b112900a653d7e61edc5ba

    Add isPersisted boolean (Needed for button settings)